### PR TITLE
add helloworldio.java_hit-1170300826

### PR DESCRIPTION
**Pull request by AlexanderChen-Real**
Let's implement helloworld using basic IO strategies in another branch,so we can work better together.

### CODE REVIEW

**Comment by BooksThinking** [comment]
that is good,i hope we can help each other in the futher

**Comment by AlexanderChen-Real** [comment]
Of course!

**Comment by BooksThinking** [comment]
i think if you can use inputstream to read this file it would be much better,like 
BufferedReader my = new BufferedReader(new FileReader(new FileInputStream("//src//helloworld.txt")));

**Comment by AlexanderChen-Real** [comment]
OK，Maybe you are right,I usually use "BufferedReader my = new BufferedReader(new FileReader("//src//helloworld.txt"));".

**Pull request merged**
